/**
 * Report exporters — CSV/Excel and PDF, both produced entirely in the browser
 * so no server-side rendering dependency is introduced.
 */

const escapeCsv = (value) => {
  const s = value === null || value === undefined ? '' : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};

function download(blob, filename) {
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

const stamp = () => new Date().toISOString().slice(0, 10);
const slug = (text) => String(text).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

/**
 * CSV with a UTF-8 BOM so Excel opens ₹ and regional product names correctly.
 */
export function exportCsv({ title, columns, rows, meta = [] }) {
  const header = [
    [title],
    ...meta.map((m) => [m]),
    [`Generated ${new Date().toLocaleString('en-IN')}`],
    [],
    columns.map((c) => c.label ?? c)
  ];

  const body = rows.map((row) =>
    columns.map((c) => {
      const key = c.key ?? c;
      const value = typeof c.value === 'function' ? c.value(row) : row[key];
      return value;
    })
  );

  const csv = [...header, ...body].map((line) => line.map(escapeCsv).join(',')).join('\r\n');
  download(new Blob([`﻿${csv}`], { type: 'text/csv;charset=utf-8;' }), `${slug(title)}-${stamp()}.csv`);
}

/**
 * PDF via a print-ready document opened in a new window. Using the browser's
 * own print pipeline keeps fonts, ₹ glyphs and page breaks correct without
 * bundling a PDF engine.
 */
export function exportPdf({ title, company, period, columns, rows, totals = null, note }) {
  const win = window.open('', '_blank', 'width=1000,height=760');
  if (!win) return;

  const th = columns
    .map((c) => `<th class="${c.align === 'right' ? 'r' : ''}">${c.label ?? c}</th>`)
    .join('');

  const tr = rows
    .map((row) => {
      const cells = columns
        .map((c) => {
          const key = c.key ?? c;
          const raw = typeof c.value === 'function' ? c.value(row) : row[key];
          return `<td class="${c.align === 'right' ? 'r' : ''}">${raw ?? ''}</td>`;
        })
        .join('');
      return `<tr>${cells}</tr>`;
    })
    .join('');

  const tfoot = totals
    ? `<tfoot><tr>${columns
        .map((c, i) => `<td class="${c.align === 'right' ? 'r' : ''} tot">${totals[i] ?? ''}</td>`)
        .join('')}</tr></tfoot>`
    : '';

  win.document.write(`<!doctype html>
<html><head><meta charset="utf-8" /><title>${title}</title>
<style>
  * { box-sizing: border-box; }
  body { font-family: -apple-system, "Segoe UI", Roboto, Arial, sans-serif; color:#111827; margin:0; padding:28px 32px; }
  header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:2px solid #4f46e5; padding-bottom:12px; margin-bottom:16px; }
  .co { font-size:17px; font-weight:700; }
  .sub { font-size:11px; color:#6b7280; margin-top:2px; }
  .title { font-size:13px; font-weight:700; text-transform:uppercase; letter-spacing:.06em; color:#4f46e5; text-align:right; }
  table { width:100%; border-collapse:collapse; font-size:11px; }
  th { text-align:left; text-transform:uppercase; font-size:9px; letter-spacing:.06em; color:#6b7280; background:#f3f4f6; padding:7px 8px; border-bottom:1px solid #d1d5db; }
  td { padding:6px 8px; border-bottom:1px solid #eef0f4; }
  .r { text-align:right; font-variant-numeric: tabular-nums; }
  tfoot .tot { font-weight:700; border-top:2px solid #9ca3af; background:#f9fafb; }
  tbody tr:nth-child(even) td { background:#fcfcfd; }
  footer { margin-top:18px; font-size:9px; color:#9ca3af; display:flex; justify-content:space-between; border-top:1px solid #e5e7eb; padding-top:8px; }
  @page { margin:14mm; }
</style></head>
<body>
  <header>
    <div>
      <div class="co">${company?.name || 'Selsolve'}</div>
      ${company?.gstin ? `<div class="sub">GSTIN: ${company.gstin}</div>` : ''}
      ${company?.city ? `<div class="sub">${company.city}${company.state ? `, ${company.state}` : ''}</div>` : ''}
    </div>
    <div>
      <div class="title">${title}</div>
      ${period ? `<div class="sub">${period}</div>` : ''}
    </div>
  </header>
  <table><thead><tr>${th}</tr></thead><tbody>${tr}</tbody>${tfoot}</table>
  ${note ? `<p style="font-size:10px;color:#6b7280;margin-top:12px;">${note}</p>` : ''}
  <footer><span>Generated by Selsolve · ${new Date().toLocaleString('en-IN')}</span><span>${rows.length} row(s)</span></footer>
  <script>window.onload = () => { window.print(); }<\/script>
</body></html>`);
  win.document.close();
}

/** Single entry point used by every report screen's export buttons. */
export function exportReport(format, payload) {
  if (format === 'pdf') return exportPdf(payload);
  return exportCsv(payload);
}
